{{- if .Values.serviceAccount.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "circleci-runner-autoscaler.fullname" . }}
  labels:
    {{- include "circleci-runner-autoscaler.labels" . | nindent 4 }}
rules:
- apiGroups:
  - v1
  - batch
  - ''
  resources:
  - pods
  - cronjobs
  - jobs
  verbs: ["*"]
{{- end }}